name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19.3

      - uses: dominikh/staticcheck-action@v1.1.0
        with:
          version: "2021.1.1"

      - name: Lint
        uses: golangci/golangci-lint-action@v3

      - name: Build
        run: go build -v ./...

      - name: Vet
        run: go vet -v ./...

      - name: Test
        run: go test -v ./...
